### ISSUE TITLE
Future of Meerkat

### ISSUE THREAD

**Issue by gsvgit** [Anastassija/Meerkat#2]
Have you any plans for the Meerkat development?

We are [working on the extension](https://github.com/YaccConstructor/Meerkat) of Meerkat which provides an ability to use combinators for graph database querying (some details may be founded [here](https://github.com/YaccConstructor/articles/blob/master/InProgress/GRADES-NDA/Semyon_combinators/paper/combinators_for_graph_querying.pdf)). Shortly: we apply parser combinators for context-free path querying.

We think that it would be great to have a common solution with a common infrastructure. Formally, our solution should be a strong extension of combinators for linear input processing (linear input is one of a case of directed graph). In practice, unification requires some effort and we want to discuss possible ways, problems, and solutions. Are you interested in collaboration?

**Comment by afroozeh** [comment]
At the moment we don't have any concrete plans to work on the Meerkat. We are currently both working full-time and also working on the thesis to defend (sometime in the summer). There are some tasks we still need to finish to make Meerkat feature complete and easier to use. I expect from the summer we will have more time to work on Meerkat.

Having said that, we are certainly interested in collaboration and very happy that you are using Meerkat. Please let us know if you are experiencing problems, have questions or need new features, or just want to discuss something about Meerkat.

**Comment by afroozeh** [comment]
I'm closing this issue. Please open new issues for specific discussions/new features or feel free to email us.
